### ISSUE TITLE
QUESTION: Translate marks

### ISSUE THREAD

**Issue by Sk1nk** [PipeItToDevNull/PLN#27]
I am VERY new to Obsidian and plan to use it for my lessons.
Since most of the color templates are not very visible at a beamer choice of colors appealed to me. I also DO like the fact, that your theme came with different marks for edit, finished, verify etc. but even if I switch the language (in my case to german) the words at the beginning stay english. 

Is there an easy way to modify or translate them?

Thanks in advance and have a great day!

**Comment by PipeItToDevNull** [comment]
Hey,

Changing this would be done with a snippet, the relevant section from PLN is below. You can copy this and turn it into a snippet changing the words "edit, unfinished, verify, or important" to your own language.

You can also easily expand this using other colours etc. 

```css
/*Red highlighter (edit)*/
mark.edit { 
    border-color: var(--color-red);
    background: rgba(var(--color-red-rgb),0.2);
}
mark.edit::before {
    color: var(--color-red);
    content: "Edit:";
}

/*Orange highlighter (unfinished)*/
mark.unfinished { 
    border-color: var(--color-orange);
    background: rgba(var(--color-orange-rgb),0.2);
}
mark.unfinished::before {
    color: var(--color-orange);
    content: "Unfinished:";
}

/*Pink highlighter (verify)*/
mark.verify { 
    border-color: var(--color-purple);
    background: rgba(var(--color-purple-rgb),0.2);
}
mark.verify::before {
    color: var(--color-purple);
    content: "Verify:";
}

/* Green highlighter (important)*/
mark.important { 
    border-color: var(--color-green);
    background: rgba(var(--color-green-rgb),0.2);
}
mark.important::before {
    color: var(--color-green);
    content: "Important:";
}
```
