### ISSUE TITLE
Provide options to decide how to display italic content (convention is inline, theme sets default to inline-block)

### ISSUE THREAD

**Issue by zzzhehao** [PipeItToDevNull/PLN#53]
At line 1324-1328 in `theme.css`, the display of italic content is set to `inline-block`, which makes obsidian constantly trying to put longer italic content in a new line for display, since it tries to reduce breaking line within the enclosed italic sentence. This is not the conventional behaviour and it makes less predictable formatting and causes unnecessary interruption while reading and writing. I believe it would be nice to let user have the option in style settings to disable this. 

In the meantime, if anyone wants to solve this too, simply changing `display: inline-block;` to `display: inline;` will do.

```css
/* more italic */
em, .cm-em {
    display: inline;
    transform: skew(-10deg);
}
```
